olimorri/codehort

client/src/App.tsx
=> hello world

client/src/components/Task/Task.tsx
=> feat(task): remove test tasks

client/src/components/Instruction/Instruction.tsx
=> feat(instruction): delete test word

client/src/components/NavBar/NavBar.tsx, client/src/containers/Lesson/Lesson.tsx
add navbar component to lesson component
=> feat(lesson/navbar): add navbar component to lesson

server/package-lock.json, server/package.json, server/src/app.module.ts, server/src/user/dto/create-user.dto.ts, server/src/user/user.controller.spec.ts, server/src/user/user.controller.ts, server/src/user/user.service.spec.ts, server/src/user/user.service.ts, server/test/app.e2e-spec.ts
Created user controller and service files
=> Backend dev

client/src/containers/Error/Error.tsx
=> feat(error.tsx): change error page content

client/src/components/CodeEditor/CodeEditor.sass, client/src/components/CodeEditor/CodeEditor.tsx
add customization to codeeditor
=> feat(codeeditor): add customization

client/src/index.style.sass, client/src/index.tsx
added a style reset sheet to index
=> style(index.tsx): add sass style reset sheet

client/src/components/LessonsOverview/LessonCard/LessonCard.sass, client/src/components/LessonsOverview/LessonCard/LessonCard.tsx, client/src/components/LessonsOverview/LessonCardList/LessonCardList.sass, client/src/components/LessonsOverview/LessonCardList/LessonCardList.tsx, client/src/containers/LessonsOverview/LessonsOverview.sass, client/src/containers/LessonsOverview/LessonsOverview.tsx
card layout for lessons overview
=> Lessons overview layout

client/src/components/Lesson/CodeEditor/validation-files/test-data.js, client/src/components/Lesson/CodeEditor/validation-files/tester.js
Added extra property in mock db, extra argument in tester() and test(), and extra test in test()
=> feat(validation): validate terminal commands

client/src/components/Lesson/CodeEditor/CodeEditor.tsx, client/src/components/Lesson/CodeEditor/validation-files/test-data.ts, client/src/components/Lesson/CodeEditor/validation-files/validator.ts
also added a string version of 'value', and console logs to handleEditorChange() in CodeEditor.tsx
=> feat(validation): refactor validator and test-data to TS

client/src/index.tsx, client/src/interfaces/hint.ts, client/src/interfaces/lesson.ts, client/src/interfaces/solution.ts, client/src/interfaces/task.ts, client/src/interfaces/user.ts, client/src/interfaces/userLesson.ts, client/src/interfaces/userTest.ts, client/src/reducers/index.ts
=> feat(client): created all interfaces, initiated store and started 

client/src/components/Lesson/Task/Task.sass, client/src/components/Lesson/Task/Task.tsx, client/src/components/Lesson/TaskList/TaskList.tsx, client/src/interfaces/componentProps.ts
add conditional styling for completed tasks
=> feat(task styling): add conditional styling

client/src/actions/userLessons.ts, client/src/components/Lesson/Instructions/Instructions.tsx, client/src/components/Lesson/Validation/test-data.ts, client/src/containers/Lesson/Lesson.tsx, client/src/lib/apiService.ts
refactor component state to global state, and stay up as late as possible
=> feat(lesson): make task explanation update

client/src/components/Lesson/Task/Task.tsx, client/src/components/Lesson/TaskList/TaskList.tsx, client/src/containers/Lesson/Lesson.tsx
change task.id prop to task.step
=> fix(tasks conditional styling): fix conditional styling

client/src/styles/variables.sass
=> style(font-size): increase $font-size-content for readability

client/src/styles/base.sass
makes the instructions more readable
=> style(text): increase line-height of p tags

client/src/components/Lesson/Validation/validator.ts
Upon completing one terminal command, progress will not be reset further back.
=> feat(validation): allow multiple terminal commands

client/src/components/Lesson/Validation/validator.ts
typo in latest validation commits. also refactored lets to consts
=> fix(validation): fix terminal validation

client/src/containers/Lesson/Lesson.tsx
=> refactor(lesson): refactor to previous commit: safe to pull

client/src/containers/Lesson/Lesson.tsx
=> Reward modal un-closeable

client/src/components/App/NavBar/NavBar.sass, client/src/components/Login/LoginForm/LoginForm.sass, client/src/components/Login/RegisterForm/RegisterForm.sass, client/src/containers/Dashboard/Dashboard.sass, client/src/containers/Landing/Landing.sass, client/src/containers/Lesson/Lesson.sass, client/src/containers/LessonsOverview/LessonsOverview.sass, client/src/containers/Login/Login.sass
- add bottom padding to all containers
- add top padding to navbar
- add finishing animation to lesson
- fix input width in register/login
=> instructions/login/all containers/navbar

client/src/components/Lesson/CodeEditor/CodeEditor.tsx, client/src/components/Lesson/LoadingMessage/LoadingMessage.sass, client/src/components/Lesson/LoadingMessage/LoadingMessage.tsx, client/src/components/index.ts, client/src/styles/index.sass
=> feat(loadingmessage): add loading message for codeditor
